"""Video baseline orchestration — runs inside the sandboxed worker (P3-S1).

Given a staged read-only video file, this runs the DD-ordered pipeline:

    ffprobe inventory (real) -> scene/shot detection (reference ffmpeg filter)
        -> bounded PTS-native frame anchors -> candidate observations
        -> audio-branch + independent-subtitle-track composition announcements

and returns a :class:`~umd.video.types.VideoOutput` structured payload
(JSON-serialized to stdout and reconstructed by the API-process runner). It
performs NO I/O and writes NO semantic state; it only produces evidence-shaped,
auditable facts. Embedded subtitle extraction is a separate
:meth:`~umd.video.dispatch_extract` boundary (P3-S2) and sub-title *parsing* is
the subtitle worker (P3-S3) — this pipeline only announces the tracks.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from umd.video.availability import video_capability_report
from umd.video.inventory import frame_anchors, probe_inventory
from umd.video.scenes import ReferenceSceneProvider
from umd.video.types import (
    VideoConfig,
    VideoObservation,
    VideoOutput,
    VideoTrack,
)

VIDEO_SEGMENTER = "umd-video"
VIDEO_DECODER = "ffmpeg"
VIDEO_RENDERER = "reference"


def _parse_fps(rate: str | None) -> float:
    """Parse ``avg_frame_rate`` of the form ``N/D`` (or ``N/1``) to a float."""
    if not rate:
        return 0.0
    if "/" in rate:
        num, _, den = rate.partition("/")
        try:
            n, d = float(num), float(den)
            return n / d if d else 0.0
        except ValueError:
            return 0.0
    try:
        return float(rate)
    except ValueError:
        return 0.0


def _video_stream(tracks: list[VideoTrack]) -> VideoTrack | None:
    for t in tracks:
        if t.codec_type == "video":
            return t
    return None


def _duration_s(tracks: list[VideoTrack]) -> float:
    v = _video_stream(tracks)
    if v is not None and v.duration:
        return v.duration
    for t in tracks:
        if t.duration:
            return t.duration
    return 0.0


def _observations(
    tracks: list[VideoTrack], scenes_count: int, shots_count: int
) -> list[VideoObservation]:
    """Bounded metadata-derived candidate observations (never canonical identity).

    All are ``candidate_kind`` evidence at low confidence, generated by the
    reference inventory. Pixel-level object/environment detection is GATED behind
    PyVA/PySceneDetect (not installed); these candidates are honest
    metadata-derived signals and never claim visual truth.
    """
    out: list[VideoObservation] = []
    v = _video_stream(tracks)
    if v is not None:
        out.append(
            VideoObservation(
                kind="environment",
                label="video stream metadata",
                confidence=0.3,
                generated_by="umd-reference-video v1.0",
                note="derived from ffprobe stream metadata; pixel vision GATED",
                quality={
                    "codec_name": v.codec_name,
                    "width": v.width,
                    "height": v.height,
                    "pix_fmt": v.pix_fmt,
                },
            )
        )
    audio_n = sum(1 for t in tracks if t.codec_type == "audio")
    out.append(
        VideoObservation(
            kind="temporal",
            label=(f"container has {scenes_count} scene(s) and {shots_count} shot(s)"),
            confidence=0.8,
            generated_by="umd-reference-video v1.0",
            note="scene/shot boundaries via ffmpeg scene filter (real)",
            quality={"scenes": scenes_count, "shots": shots_count},
        )
    )
    if audio_n:
        out.append(
            VideoObservation(
                kind="environment",
                label=(f"container has {audio_n} audio track(s); composed via audio baseline"),
                confidence=0.9,
                generated_by="umd-reference-video v1.0",
                quality={"audio_tracks": audio_n},
            )
        )
    return out


class VideoPipeline:
    """The deterministic video baseline (worker-side, no I/O)."""

    provider_version = "umd-video-reference v1.0"

    def __init__(self, input_path: Path, config: VideoConfig) -> None:
        self.input_path = input_path
        self.config = config

    def run(self) -> VideoOutput:
        tracks = probe_inventory(self.input_path, max_duration_s=self.config.max_duration_s)
        duration_s = _duration_s(tracks)
        scenes, shots = ReferenceSceneProvider().detect(self.input_path, self.config, duration_s)
        vstream = _video_stream(tracks)
        fps = _parse_fps(vstream.avg_frame_rate if vstream else None)
        anchors = frame_anchors(self.input_path, self.config, fps, duration_s)
        audio_tracks = [
            {
                "index": t.index,
                "codec_name": t.codec_name,
                "language": t.language,
                "title": t.title,
                "sample_rate": t.sample_rate,
                "channels": t.channels,
                "pts_start": t.pts_start,
            }
            for t in tracks
            if t.codec_type == "audio"
        ]
        subtitle_tracks = [
            {
                "index": t.index,
                "codec_name": t.codec_name,
                "language": t.language,
                "title": t.title,
                "disposition": t.disposition,
            }
            for t in tracks
            if t.codec_type == "subtitle"
        ]
        return VideoOutput(
            meta=_meta_dict(tracks, duration_s),
            timing=_timing_dict(tracks, duration_s, fps),
            inventory=tracks,
            scenes=scenes,
            shots=shots,
            frame_anchors=anchors,
            observations=_observations(tracks, len(scenes), len(shots)),
            audio_tracks=audio_tracks,
            subtitle_tracks=subtitle_tracks,
            capabilities=video_capability_report(self.config),
            warnings=_warnings(tracks),
        )


def _warnings(tracks: list[VideoTrack]) -> list[str]:
    out: list[str] = []
    bitmap = [
        t
        for t in tracks
        if t.codec_type == "subtitle"
        and t.codec_name
        not in (
            "subrip",
            "ssa",
            "ass",
            "webvtt",
            "mov_text",
            "text",
            "sami",
        )
    ]
    if bitmap:
        out.append(
            f"{len(bitmap)} bitmap subtitle track(s) classified for quarantine "
            "(not text-extractable)"
        )
    if not any(t.codec_type == "video" for t in tracks):
        out.append("container has no video stream")
    return out


def _meta_dict(tracks: list[VideoTrack], duration_s: float) -> dict[str, Any]:
    v = _video_stream(tracks)
    return {
        "duration_s": round(duration_s, 4),
        "stream_count": len(tracks),
        "video_codec": v.codec_name if v else None,
        "decoder": VIDEO_DECODER,
        "renderer": VIDEO_RENDERER,
    }


def _timing_dict(tracks: list[VideoTrack], duration_s: float, fps: float) -> dict[str, Any]:
    v = _video_stream(tracks)
    return {
        "duration_s": round(duration_s, 4),
        "fps": round(fps, 4) if fps else None,
        "time_base": v.time_base if v else None,
        "avg_frame_rate": v.avg_frame_rate if v else None,
        "decoded": "reference-inventory",
    }


__all__ = [
    "VIDEO_DECODER",
    "VIDEO_RENDERER",
    "VIDEO_SEGMENTER",
    "VideoPipeline",
]
